/*
Deployment script for dd

This code was generated by a tool.
Changes to this file may cause incorrect behavior and will be lost if
the code is regenerated.
*/

GO
SET ANSI_NULLS, ANSI_PADDING, ANSI_WARNINGS, ARITHABORT, CONCAT_NULL_YIELDS_NULL, QUOTED_IDENTIFIER ON;

SET NUMERIC_ROUNDABORT OFF;


GO
:setvar DatabaseName "dd"
:setvar DefaultFilePrefix "dd"
:setvar DefaultDataPath "C:\Users\klamc\AppData\Local\Microsoft\Microsoft SQL Server Local DB\Instances\MSSQLLocalDB\"
:setvar DefaultLogPath "C:\Users\klamc\AppData\Local\Microsoft\Microsoft SQL Server Local DB\Instances\MSSQLLocalDB\"

GO
:on error exit
GO
/*
Detect SQLCMD mode and disable script execution if SQLCMD mode is not supported.
To re-enable the script after enabling SQLCMD mode, execute the following:
SET NOEXEC OFF; 
*/
:setvar __IsSqlCmdEnabled "True"
GO
IF N'$(__IsSqlCmdEnabled)' NOT LIKE N'True'
    BEGIN
        PRINT N'SQLCMD mode must be enabled to successfully execute this script.';
        SET NOEXEC ON;
    END


GO
IF EXISTS (SELECT 1
           FROM   [master].[dbo].[sysdatabases]
           WHERE  [name] = N'$(DatabaseName)')
    BEGIN
        ALTER DATABASE [$(DatabaseName)]
            SET AUTO_CLOSE ON 
            WITH ROLLBACK IMMEDIATE;
    END


GO
USE [$(DatabaseName)];


GO
PRINT N'Creating Table [dbo].[__EFMigrationsHistory]...';


GO
CREATE TABLE [dbo].[__EFMigrationsHistory] (
    [MigrationId]    NVARCHAR (150) NOT NULL,
    [ProductVersion] NVARCHAR (32)  NOT NULL,
    CONSTRAINT [PK___EFMigrationsHistory] PRIMARY KEY CLUSTERED ([MigrationId] ASC)
);


GO
PRINT N'Creating Table [dbo].[Addresses]...';


GO
CREATE TABLE [dbo].[Addresses] (
    [Id]          INT           IDENTITY (1, 1) NOT NULL,
    [CustomerId]  INT           NOT NULL,
    [CountryId]   INT           NULL,
    [Street]      VARCHAR (100) NULL,
    [HouseNumber] VARCHAR (20)  NULL,
    [FlatNumber]  VARCHAR (20)  NULL,
    [City]        VARCHAR (50)  NULL,
    [State]       VARCHAR (50)  NULL,
    [PostalCode]  VARCHAR (10)  NULL,
    [IsActive]    BIT           NOT NULL,
    [DateCreated] DATETIME      NULL,
    [DateUpdated] DATETIME      NULL,
    [DateDeleted] DATETIME      NULL,
    CONSTRAINT [PK__Addresse__3214EC073E442168] PRIMARY KEY CLUSTERED ([Id] ASC)
);


GO
PRINT N'Creating Index [dbo].[Addresses].[IX_Addresses_CountryId]...';


GO
CREATE NONCLUSTERED INDEX [IX_Addresses_CountryId]
    ON [dbo].[Addresses]([CountryId] ASC);


GO
PRINT N'Creating Index [dbo].[Addresses].[IX_Addresses_CustomerId]...';


GO
CREATE NONCLUSTERED INDEX [IX_Addresses_CustomerId]
    ON [dbo].[Addresses]([CustomerId] ASC);


GO
PRINT N'Creating Table [dbo].[Categories]...';


GO
CREATE TABLE [dbo].[Categories] (
    [Id]          INT            IDENTITY (1, 1) NOT NULL,
    [Code]        NVARCHAR (MAX) NOT NULL,
    [Name]        NVARCHAR (20)  NOT NULL,
    [About]       NVARCHAR (500) NOT NULL,
    [IsActive]    BIT            NOT NULL,
    [DateCreated] DATETIME       NULL,
    [DateUpdated] DATETIME       NULL,
    [DateDeleted] DATETIME       NULL,
    CONSTRAINT [PK__Categori__3214EC078E66F864] PRIMARY KEY CLUSTERED ([Id] ASC)
);


GO
PRINT N'Creating Table [dbo].[Countries]...';


GO
CREATE TABLE [dbo].[Countries] (
    [Id]          INT          IDENTITY (1, 1) NOT NULL,
    [CountryName] VARCHAR (50) NOT NULL,
    [CountryCode] VARCHAR (5)  NOT NULL,
    [IsActive]    BIT          NOT NULL,
    [DateCreated] DATETIME     NULL,
    [DateUpdated] DATETIME     NULL,
    [DateDeleted] DATETIME     NULL,
    CONSTRAINT [PK__Countrie__3214EC07C996EFAA] PRIMARY KEY CLUSTERED ([Id] ASC)
);


GO
PRINT N'Creating Index [dbo].[Countries].[UQ__Countrie__5D9B0D2C9915823B]...';


GO
CREATE UNIQUE NONCLUSTERED INDEX [UQ__Countrie__5D9B0D2C9915823B]
    ON [dbo].[Countries]([CountryCode] ASC);


GO
PRINT N'Creating Index [dbo].[Countries].[UQ__Countrie__E056F201CC4E645C]...';


GO
CREATE UNIQUE NONCLUSTERED INDEX [UQ__Countrie__E056F201CC4E645C]
    ON [dbo].[Countries]([CountryName] ASC);


GO
PRINT N'Creating Table [dbo].[Customers]...';


GO
CREATE TABLE [dbo].[Customers] (
    [Id]          INT            IDENTITY (1, 1) NOT NULL,
    [UserId]      NVARCHAR (450) NOT NULL,
    [Points]      INT            NULL,
    [Nip]         VARCHAR (50)   NULL,
    [IsActive]    BIT            NOT NULL,
    [DateCreated] DATETIME       NULL,
    [DateUpdated] DATETIME       NULL,
    [DateDeleted] DATETIME       NULL,
    CONSTRAINT [PK__Customer__3214EC07EFBD2E72] PRIMARY KEY CLUSTERED ([Id] ASC)
);


GO
PRINT N'Creating Index [dbo].[Customers].[IX_Customers_UserId]...';


GO
CREATE NONCLUSTERED INDEX [IX_Customers_UserId]
    ON [dbo].[Customers]([UserId] ASC);


GO
PRINT N'Creating Table [dbo].[DeliveryMethodOrders]...';


GO
CREATE TABLE [dbo].[DeliveryMethodOrders] (
    [DeliveryMethodId] INT      NOT NULL,
    [OrderId]          INT      NOT NULL,
    [IsActive]         BIT      NOT NULL,
    [DateCreated]      DATETIME NULL,
    [DateUpdated]      DATETIME NULL,
    [DateDeleted]      DATETIME NULL,
    CONSTRAINT [PK__Delivery__973AA5FED03E982C] PRIMARY KEY CLUSTERED ([DeliveryMethodId] ASC, [OrderId] ASC)
);


GO
PRINT N'Creating Index [dbo].[DeliveryMethodOrders].[IX_DeliveryMethodOrders_OrderId]...';


GO
CREATE NONCLUSTERED INDEX [IX_DeliveryMethodOrders_OrderId]
    ON [dbo].[DeliveryMethodOrders]([OrderId] ASC);


GO
PRINT N'Creating Table [dbo].[DeliveryMethods]...';


GO
CREATE TABLE [dbo].[DeliveryMethods] (
    [Id]          INT          IDENTITY (1, 1) NOT NULL,
    [MethodName]  VARCHAR (50) NOT NULL,
    [IsActive]    BIT          NOT NULL,
    [DateCreated] DATETIME     NULL,
    [DateUpdated] DATETIME     NULL,
    [DateDeleted] DATETIME     NULL,
    [Cost]        MONEY        NOT NULL,
    CONSTRAINT [PK__Delivery__3214EC07AE1385C7] PRIMARY KEY CLUSTERED ([Id] ASC)
);


GO
PRINT N'Creating Table [dbo].[Invoice]...';


GO
CREATE TABLE [dbo].[Invoice] (
    [Id]          INT          IDENTITY (1, 1) NOT NULL,
    [CustomerId]  INT          NOT NULL,
    [Number]      VARCHAR (25) NOT NULL,
    [DateOfIssue] DATETIME     NOT NULL,
    [PaymentId]   INT          NULL,
    [IsPaid]      BIT          NOT NULL,
    [IsActive]    BIT          NOT NULL,
    [DateCreated] DATETIME     NULL,
    [DateUpdated] DATETIME     NULL,
    [DateDeleted] DATETIME     NULL,
    CONSTRAINT [PK__Invoice__3214EC07E196B1F5] PRIMARY KEY CLUSTERED ([Id] ASC)
);


GO
PRINT N'Creating Index [dbo].[Invoice].[IX_Invoice_CustomerId]...';


GO
CREATE NONCLUSTERED INDEX [IX_Invoice_CustomerId]
    ON [dbo].[Invoice]([CustomerId] ASC);


GO
PRINT N'Creating Index [dbo].[Invoice].[IX_Invoice_PaymentId]...';


GO
CREATE NONCLUSTERED INDEX [IX_Invoice_PaymentId]
    ON [dbo].[Invoice]([PaymentId] ASC);


GO
PRINT N'Creating Table [dbo].[InvoiceItem]...';


GO
CREATE TABLE [dbo].[InvoiceItem] (
    [Id]               INT          IDENTITY (1, 1) NOT NULL,
    [InvoiceId]        INT          NOT NULL,
    [ProductId]        INT          NOT NULL,
    [BasePricePerUnit] DECIMAL (18) NOT NULL,
    [TaxRate]          FLOAT (53)   NOT NULL,
    [Quantity]         FLOAT (53)   NOT NULL,
    [Discount]         FLOAT (53)   NOT NULL,
    [IsActive]         BIT          NOT NULL,
    [DateCreated]      DATETIME     NULL,
    [DateUpdated]      DATETIME     NULL,
    [DateDeleted]      DATETIME     NULL,
    CONSTRAINT [PK__InvoiceI__3214EC07847050C4] PRIMARY KEY CLUSTERED ([Id] ASC)
);


GO
PRINT N'Creating Index [dbo].[InvoiceItem].[IX_InvoiceItem_InvoiceId]...';


GO
CREATE NONCLUSTERED INDEX [IX_InvoiceItem_InvoiceId]
    ON [dbo].[InvoiceItem]([InvoiceId] ASC);


GO
PRINT N'Creating Index [dbo].[InvoiceItem].[IX_InvoiceItem_ProductId]...';


GO
CREATE NONCLUSTERED INDEX [IX_InvoiceItem_ProductId]
    ON [dbo].[InvoiceItem]([ProductId] ASC);


GO
PRINT N'Creating Table [dbo].[OrderItems]...';


GO
CREATE TABLE [dbo].[OrderItems] (
    [Id]          INT      IDENTITY (1, 1) NOT NULL,
    [OrderId]     INT      NOT NULL,
    [ProductId]   INT      NOT NULL,
    [Quantity]    INT      NOT NULL,
    [UnitPrice]   MONEY    NOT NULL,
    [IsActive]    BIT      NOT NULL,
    [DateCreated] DATETIME NULL,
    [DateUpdated] DATETIME NULL,
    [DateDeleted] DATETIME NULL,
    PRIMARY KEY CLUSTERED ([Id] ASC)
);


GO
PRINT N'Creating Table [dbo].[Orders]...';


GO
CREATE TABLE [dbo].[Orders] (
    [Id]          INT           IDENTITY (1, 1) NOT NULL,
    [Code]        NVARCHAR (50) NOT NULL,
    [CustomerId]  INT           NOT NULL,
    [OrderDate]   DATETIME      NOT NULL,
    [TotalAmount] MONEY         NOT NULL,
    [Status]      VARCHAR (20)  NOT NULL,
    [IsActive]    BIT           NOT NULL,
    [DateCreated] DATETIME      NULL,
    [DateUpdated] DATETIME      NULL,
    [DateDeleted] DATETIME      NULL,
    [IsPaid]      BIT           NOT NULL,
    CONSTRAINT [PK__Orders__3214EC07C807C4CC] PRIMARY KEY CLUSTERED ([Id] ASC)
);


GO
PRINT N'Creating Index [dbo].[Orders].[IX_Orders_CustomerId]...';


GO
CREATE NONCLUSTERED INDEX [IX_Orders_CustomerId]
    ON [dbo].[Orders]([CustomerId] ASC);


GO
PRINT N'Creating Table [dbo].[PaymentMethods]...';


GO
CREATE TABLE [dbo].[PaymentMethods] (
    [Id]          INT           IDENTITY (1, 1) NOT NULL,
    [PaymentType] VARCHAR (50)  NOT NULL,
    [Details]     VARCHAR (100) NULL,
    [IsActive]    BIT           NOT NULL,
    [DateCreated] DATETIME      NULL,
    [DateUpdated] DATETIME      NULL,
    [DateDeleted] DATETIME      NULL,
    CONSTRAINT [PK__PaymentM__3214EC07B7569BC7] PRIMARY KEY CLUSTERED ([Id] ASC)
);


GO
PRINT N'Creating Table [dbo].[Payments]...';


GO
CREATE TABLE [dbo].[Payments] (
    [Id]              INT      IDENTITY (1, 1) NOT NULL,
    [OrderId]         INT      NULL,
    [PaymentMethodId] INT      NULL,
    [Amount]          MONEY    NOT NULL,
    [PaymentDate]     DATETIME NOT NULL,
    [IsActive]        BIT      NOT NULL,
    [DateCreated]     DATETIME NULL,
    [DateUpdated]     DATETIME NULL,
    [DateDeleted]     DATETIME NULL,
    CONSTRAINT [PK__Payments__3214EC07287FE367] PRIMARY KEY CLUSTERED ([Id] ASC)
);


GO
PRINT N'Creating Index [dbo].[Payments].[IX_Payments_OrderId]...';


GO
CREATE NONCLUSTERED INDEX [IX_Payments_OrderId]
    ON [dbo].[Payments]([OrderId] ASC);


GO
PRINT N'Creating Index [dbo].[Payments].[IX_Payments_PaymentMethodId]...';


GO
CREATE NONCLUSTERED INDEX [IX_Payments_PaymentMethodId]
    ON [dbo].[Payments]([PaymentMethodId] ASC);


GO
PRINT N'Creating Table [dbo].[ProductCategories]...';


GO
CREATE TABLE [dbo].[ProductCategories] (
    [ProductId]   INT      NOT NULL,
    [CategoryId]  INT      NOT NULL,
    [IsActive]    BIT      NOT NULL,
    [DateCreated] DATETIME NOT NULL,
    [DateUpdated] DATETIME NOT NULL,
    [DateDeleted] DATETIME NOT NULL,
    CONSTRAINT [PK__ProductC__159C556D1A2729F4] PRIMARY KEY CLUSTERED ([ProductId] ASC, [CategoryId] ASC)
);


GO
PRINT N'Creating Index [dbo].[ProductCategories].[IX_ProductCategories_CategoryId]...';


GO
CREATE NONCLUSTERED INDEX [IX_ProductCategories_CategoryId]
    ON [dbo].[ProductCategories]([CategoryId] ASC);


GO
PRINT N'Creating Table [dbo].[Products]...';


GO
CREATE TABLE [dbo].[Products] (
    [Id]            INT             IDENTITY (1, 1) NOT NULL,
    [Name]          NVARCHAR (100)  NOT NULL,
    [Brand]         NVARCHAR (50)   NOT NULL,
    [Code]          NVARCHAR (30)   NOT NULL,
    [Price]         DECIMAL (10, 2) NULL,
    [OldPrice]      DECIMAL (18, 2) NULL,
    [About]         NVARCHAR (500)  NULL,
    [LongAbout]     NVARCHAR (2000) NOT NULL,
    [RatingSum]     INT             NULL,
    [RatingVotes]   INT             NULL,
    [Photo]         NVARCHAR (255)  NULL,
    [OtherPhotos]   NVARCHAR (1000) NULL,
    [Stock]         INT             NOT NULL,
    [SubcategoryId] INT             NOT NULL,
    [IsActive]      BIT             NOT NULL,
    [DateCreated]   DATETIME        NULL,
    [DateUpdated]   DATETIME        NULL,
    [DateDeleted]   DATETIME        NULL,
    CONSTRAINT [PK__Products__3214EC07159B8D3E] PRIMARY KEY CLUSTERED ([Id] ASC)
);


GO
PRINT N'Creating Index [dbo].[Products].[IX_Products_SubcategoryId]...';


GO
CREATE NONCLUSTERED INDEX [IX_Products_SubcategoryId]
    ON [dbo].[Products]([SubcategoryId] ASC);


GO
PRINT N'Creating Table [dbo].[Reviews]...';


GO
CREATE TABLE [dbo].[Reviews] (
    [Id]          INT      IDENTITY (1, 1) NOT NULL,
    [ProductId]   INT      NOT NULL,
    [CustomerId]  INT      NOT NULL,
    [Rating]      INT      NOT NULL,
    [ReviewText]  TEXT     NOT NULL,
    [IsActive]    BIT      NOT NULL,
    [DateCreated] DATETIME NULL,
    [DateUpdated] DATETIME NULL,
    [DateDeleted] DATETIME NULL,
    CONSTRAINT [PK__Reviews__3214EC077DA90771] PRIMARY KEY CLUSTERED ([Id] ASC)
);


GO
PRINT N'Creating Index [dbo].[Reviews].[IX_Reviews_CustomerId]...';


GO
CREATE NONCLUSTERED INDEX [IX_Reviews_CustomerId]
    ON [dbo].[Reviews]([CustomerId] ASC);


GO
PRINT N'Creating Index [dbo].[Reviews].[IX_Reviews_ProductId]...';


GO
CREATE NONCLUSTERED INDEX [IX_Reviews_ProductId]
    ON [dbo].[Reviews]([ProductId] ASC);


GO
PRINT N'Creating Table [dbo].[RoleClaims]...';


GO
CREATE TABLE [dbo].[RoleClaims] (
    [Id]         INT            IDENTITY (1, 1) NOT NULL,
    [RoleId]     NVARCHAR (MAX) NULL,
    [ClaimType]  NVARCHAR (MAX) NULL,
    [ClaimValue] NVARCHAR (MAX) NULL,
    CONSTRAINT [PK_RoleClaims] PRIMARY KEY CLUSTERED ([Id] ASC)
);


GO
PRINT N'Creating Table [dbo].[Roles]...';


GO
CREATE TABLE [dbo].[Roles] (
    [Id]               NVARCHAR (450) NOT NULL,
    [Name]             NVARCHAR (MAX) NULL,
    [NormalizedName]   NVARCHAR (MAX) NULL,
    [ConcurrencyStamp] NVARCHAR (MAX) NULL,
    CONSTRAINT [PK_Roles] PRIMARY KEY CLUSTERED ([Id] ASC)
);


GO
PRINT N'Creating Table [dbo].[Shipments]...';


GO
CREATE TABLE [dbo].[Shipments] (
    [Id]                   INT      IDENTITY (1, 1) NOT NULL,
    [OrderId]              INT      NOT NULL,
    [DeliveryMethodId]     INT      NOT NULL,
    [ShipmentDate]         DATETIME NOT NULL,
    [EstimatedArrivalDate] DATETIME NOT NULL,
    [IsActive]             BIT      NOT NULL,
    [DateCreated]          DATETIME NULL,
    [DateUpdated]          DATETIME NULL,
    [DateDeleted]          DATETIME NULL,
    CONSTRAINT [PK__Shipment__3214EC079EE2232D] PRIMARY KEY CLUSTERED ([Id] ASC)
);


GO
PRINT N'Creating Index [dbo].[Shipments].[IX_Shipments_DeliveryMethodId]...';


GO
CREATE NONCLUSTERED INDEX [IX_Shipments_DeliveryMethodId]
    ON [dbo].[Shipments]([DeliveryMethodId] ASC);


GO
PRINT N'Creating Index [dbo].[Shipments].[IX_Shipments_OrderId]...';


GO
CREATE NONCLUSTERED INDEX [IX_Shipments_OrderId]
    ON [dbo].[Shipments]([OrderId] ASC);


GO
PRINT N'Creating Table [dbo].[ShoppingCartItems]...';


GO
CREATE TABLE [dbo].[ShoppingCartItems] (
    [Id]             INT           IDENTITY (1, 1) NOT NULL,
    [ProductId]      INT           NOT NULL,
    [Amount]         INT           NOT NULL,
    [ShoppingCartId] NVARCHAR (50) NOT NULL,
    [IsActive]       BIT           NOT NULL,
    [DateCreated]    DATETIME      NULL,
    [DateUpdated]    DATETIME      NULL,
    [DateDeleted]    DATETIME      NULL,
    CONSTRAINT [PK_ShoppingCartItems] PRIMARY KEY CLUSTERED ([Id] ASC)
);


GO
PRINT N'Creating Index [dbo].[ShoppingCartItems].[IX_ShoppingCartItems_ProductId]...';


GO
CREATE NONCLUSTERED INDEX [IX_ShoppingCartItems_ProductId]
    ON [dbo].[ShoppingCartItems]([ProductId] ASC);


GO
PRINT N'Creating Table [dbo].[Subcategories]...';


GO
CREATE TABLE [dbo].[Subcategories] (
    [Id]          INT            IDENTITY (1, 1) NOT NULL,
    [Code]        NVARCHAR (20)  NOT NULL,
    [Name]        NVARCHAR (100) NOT NULL,
    [About]       NVARCHAR (500) NOT NULL,
    [CategoryId]  INT            NOT NULL,
    [IsActive]    BIT            NOT NULL,
    [DateCreated] DATETIME       NULL,
    [DateUpdated] DATETIME       NULL,
    [DateDeleted] DATETIME       NULL,
    CONSTRAINT [PK_Subcategories] PRIMARY KEY CLUSTERED ([Id] ASC)
);


GO
PRINT N'Creating Index [dbo].[Subcategories].[IX_Subcategories_CategoryId]...';


GO
CREATE NONCLUSTERED INDEX [IX_Subcategories_CategoryId]
    ON [dbo].[Subcategories]([CategoryId] ASC);


GO
PRINT N'Creating Table [dbo].[UserClaims]...';


GO
CREATE TABLE [dbo].[UserClaims] (
    [Id]         INT            IDENTITY (1, 1) NOT NULL,
    [UserId]     NVARCHAR (MAX) NULL,
    [ClaimType]  NVARCHAR (MAX) NULL,
    [ClaimValue] NVARCHAR (MAX) NULL,
    CONSTRAINT [PK_UserClaims] PRIMARY KEY CLUSTERED ([Id] ASC)
);


GO
PRINT N'Creating Table [dbo].[UserLogins]...';


GO
CREATE TABLE [dbo].[UserLogins] (
    [LoginProvider]       NVARCHAR (450) NOT NULL,
    [ProviderKey]         NVARCHAR (450) NOT NULL,
    [UserId]              NVARCHAR (450) NOT NULL,
    [ProviderDisplayName] NVARCHAR (MAX) NULL,
    CONSTRAINT [PK_UserLogins] PRIMARY KEY CLUSTERED ([UserId] ASC, [LoginProvider] ASC, [ProviderKey] ASC)
);


GO
PRINT N'Creating Table [dbo].[UserRoles]...';


GO
CREATE TABLE [dbo].[UserRoles] (
    [UserId] NVARCHAR (450) NOT NULL,
    [RoleId] NVARCHAR (450) NOT NULL,
    CONSTRAINT [PK_UserRoles] PRIMARY KEY CLUSTERED ([UserId] ASC, [RoleId] ASC)
);


GO
PRINT N'Creating Table [dbo].[Users]...';


GO
CREATE TABLE [dbo].[Users] (
    [Id]                   NVARCHAR (450)     NOT NULL,
    [FullName]             NVARCHAR (MAX)     NOT NULL,
    [Role]                 NVARCHAR (MAX)     NOT NULL,
    [IsAdmin]              BIT                NOT NULL,
    [IsActive]             BIT                NOT NULL,
    [DateCreated]          DATETIME2 (7)      NOT NULL,
    [DateUpdated]          DATETIME2 (7)      NOT NULL,
    [DateDeleted]          DATETIME2 (7)      NOT NULL,
    [UserName]             NVARCHAR (MAX)     NULL,
    [NormalizedUserName]   NVARCHAR (MAX)     NULL,
    [Email]                NVARCHAR (MAX)     NULL,
    [NormalizedEmail]      NVARCHAR (MAX)     NULL,
    [EmailConfirmed]       BIT                NOT NULL,
    [PasswordHash]         NVARCHAR (MAX)     NULL,
    [SecurityStamp]        NVARCHAR (MAX)     NULL,
    [ConcurrencyStamp]     NVARCHAR (MAX)     NULL,
    [PhoneNumber]          NVARCHAR (MAX)     NULL,
    [PhoneNumberConfirmed] BIT                NOT NULL,
    [TwoFactorEnabled]     BIT                NOT NULL,
    [LockoutEnd]           DATETIMEOFFSET (7) NULL,
    [LockoutEnabled]       BIT                NOT NULL,
    [AccessFailedCount]    INT                NOT NULL,
    [FirstName]            NVARCHAR (MAX)     NOT NULL,
    [LastName]             NVARCHAR (MAX)     NOT NULL,
    [IsAuthenticated]      BIT                NOT NULL,
    CONSTRAINT [PK_Users] PRIMARY KEY CLUSTERED ([Id] ASC)
);


GO
PRINT N'Creating Table [dbo].[UserTokens]...';


GO
CREATE TABLE [dbo].[UserTokens] (
    [UserId]        NVARCHAR (450) NOT NULL,
    [LoginProvider] NVARCHAR (450) NOT NULL,
    [Name]          NVARCHAR (450) NOT NULL,
    [Value]         NVARCHAR (MAX) NULL,
    CONSTRAINT [PK_UserTokens] PRIMARY KEY CLUSTERED ([UserId] ASC, [LoginProvider] ASC, [Name] ASC)
);


GO
PRINT N'Creating Default Constraint unnamed constraint on [dbo].[Addresses]...';


GO
ALTER TABLE [dbo].[Addresses]
    ADD DEFAULT (getdate()) FOR [DateDeleted];


GO
PRINT N'Creating Default Constraint unnamed constraint on [dbo].[Addresses]...';


GO
ALTER TABLE [dbo].[Addresses]
    ADD DEFAULT (getdate()) FOR [DateCreated];


GO
PRINT N'Creating Default Constraint unnamed constraint on [dbo].[Addresses]...';


GO
ALTER TABLE [dbo].[Addresses]
    ADD DEFAULT (CONVERT([bit],(1))) FOR [IsActive];


GO
PRINT N'Creating Default Constraint unnamed constraint on [dbo].[Addresses]...';


GO
ALTER TABLE [dbo].[Addresses]
    ADD DEFAULT (getdate()) FOR [DateUpdated];


GO
PRINT N'Creating Default Constraint unnamed constraint on [dbo].[Categories]...';


GO
ALTER TABLE [dbo].[Categories]
    ADD DEFAULT (CONVERT([bit],(1))) FOR [IsActive];


GO
PRINT N'Creating Default Constraint unnamed constraint on [dbo].[Categories]...';


GO
ALTER TABLE [dbo].[Categories]
    ADD DEFAULT (getdate()) FOR [DateUpdated];


GO
PRINT N'Creating Default Constraint unnamed constraint on [dbo].[Categories]...';


GO
ALTER TABLE [dbo].[Categories]
    ADD DEFAULT (getdate()) FOR [DateDeleted];


GO
PRINT N'Creating Default Constraint unnamed constraint on [dbo].[Categories]...';


GO
ALTER TABLE [dbo].[Categories]
    ADD DEFAULT (getdate()) FOR [DateCreated];


GO
PRINT N'Creating Default Constraint unnamed constraint on [dbo].[Countries]...';


GO
ALTER TABLE [dbo].[Countries]
    ADD DEFAULT (getdate()) FOR [DateUpdated];


GO
PRINT N'Creating Default Constraint unnamed constraint on [dbo].[Countries]...';


GO
ALTER TABLE [dbo].[Countries]
    ADD DEFAULT (getdate()) FOR [DateDeleted];


GO
PRINT N'Creating Default Constraint unnamed constraint on [dbo].[Countries]...';


GO
ALTER TABLE [dbo].[Countries]
    ADD DEFAULT (getdate()) FOR [DateCreated];


GO
PRINT N'Creating Default Constraint unnamed constraint on [dbo].[Countries]...';


GO
ALTER TABLE [dbo].[Countries]
    ADD DEFAULT (CONVERT([bit],(1))) FOR [IsActive];


GO
PRINT N'Creating Default Constraint unnamed constraint on [dbo].[Customers]...';


GO
ALTER TABLE [dbo].[Customers]
    ADD DEFAULT (getdate()) FOR [DateUpdated];


GO
PRINT N'Creating Default Constraint unnamed constraint on [dbo].[Customers]...';


GO
ALTER TABLE [dbo].[Customers]
    ADD DEFAULT (getdate()) FOR [DateDeleted];


GO
PRINT N'Creating Default Constraint unnamed constraint on [dbo].[Customers]...';


GO
ALTER TABLE [dbo].[Customers]
    ADD DEFAULT ((0)) FOR [Points];


GO
PRINT N'Creating Default Constraint unnamed constraint on [dbo].[Customers]...';


GO
ALTER TABLE [dbo].[Customers]
    ADD DEFAULT (getdate()) FOR [DateCreated];


GO
PRINT N'Creating Default Constraint unnamed constraint on [dbo].[Customers]...';


GO
ALTER TABLE [dbo].[Customers]
    ADD DEFAULT (CONVERT([bit],(1))) FOR [IsActive];


GO
PRINT N'Creating Default Constraint unnamed constraint on [dbo].[DeliveryMethodOrders]...';


GO
ALTER TABLE [dbo].[DeliveryMethodOrders]
    ADD DEFAULT (CONVERT([bit],(1))) FOR [IsActive];


GO
PRINT N'Creating Default Constraint unnamed constraint on [dbo].[DeliveryMethodOrders]...';


GO
ALTER TABLE [dbo].[DeliveryMethodOrders]
    ADD DEFAULT (getdate()) FOR [DateCreated];


GO
PRINT N'Creating Default Constraint unnamed constraint on [dbo].[DeliveryMethodOrders]...';


GO
ALTER TABLE [dbo].[DeliveryMethodOrders]
    ADD DEFAULT (getdate()) FOR [DateUpdated];


GO
PRINT N'Creating Default Constraint unnamed constraint on [dbo].[DeliveryMethodOrders]...';


GO
ALTER TABLE [dbo].[DeliveryMethodOrders]
    ADD DEFAULT (getdate()) FOR [DateDeleted];


GO
PRINT N'Creating Default Constraint unnamed constraint on [dbo].[DeliveryMethods]...';


GO
ALTER TABLE [dbo].[DeliveryMethods]
    ADD DEFAULT (CONVERT([bit],(1))) FOR [IsActive];


GO
PRINT N'Creating Default Constraint unnamed constraint on [dbo].[DeliveryMethods]...';


GO
ALTER TABLE [dbo].[DeliveryMethods]
    ADD DEFAULT (getdate()) FOR [DateUpdated];


GO
PRINT N'Creating Default Constraint unnamed constraint on [dbo].[DeliveryMethods]...';


GO
ALTER TABLE [dbo].[DeliveryMethods]
    ADD DEFAULT (getdate()) FOR [DateDeleted];


GO
PRINT N'Creating Default Constraint unnamed constraint on [dbo].[DeliveryMethods]...';


GO
ALTER TABLE [dbo].[DeliveryMethods]
    ADD DEFAULT (getdate()) FOR [DateCreated];


GO
PRINT N'Creating Default Constraint unnamed constraint on [dbo].[DeliveryMethods]...';


GO
ALTER TABLE [dbo].[DeliveryMethods]
    ADD DEFAULT ((0.0)) FOR [Cost];


GO
PRINT N'Creating Default Constraint unnamed constraint on [dbo].[Invoice]...';


GO
ALTER TABLE [dbo].[Invoice]
    ADD DEFAULT (getdate()) FOR [DateUpdated];


GO
PRINT N'Creating Default Constraint unnamed constraint on [dbo].[Invoice]...';


GO
ALTER TABLE [dbo].[Invoice]
    ADD DEFAULT (getdate()) FOR [DateDeleted];


GO
PRINT N'Creating Default Constraint unnamed constraint on [dbo].[Invoice]...';


GO
ALTER TABLE [dbo].[Invoice]
    ADD DEFAULT (getdate()) FOR [DateCreated];


GO
PRINT N'Creating Default Constraint unnamed constraint on [dbo].[Invoice]...';


GO
ALTER TABLE [dbo].[Invoice]
    ADD DEFAULT (CONVERT([bit],(1))) FOR [IsActive];


GO
PRINT N'Creating Default Constraint unnamed constraint on [dbo].[InvoiceItem]...';


GO
ALTER TABLE [dbo].[InvoiceItem]
    ADD DEFAULT (CONVERT([bit],(1))) FOR [IsActive];


GO
PRINT N'Creating Default Constraint unnamed constraint on [dbo].[InvoiceItem]...';


GO
ALTER TABLE [dbo].[InvoiceItem]
    ADD DEFAULT (getdate()) FOR [DateUpdated];


GO
PRINT N'Creating Default Constraint unnamed constraint on [dbo].[InvoiceItem]...';


GO
ALTER TABLE [dbo].[InvoiceItem]
    ADD DEFAULT (getdate()) FOR [DateDeleted];


GO
PRINT N'Creating Default Constraint unnamed constraint on [dbo].[InvoiceItem]...';


GO
ALTER TABLE [dbo].[InvoiceItem]
    ADD DEFAULT (getdate()) FOR [DateCreated];


GO
PRINT N'Creating Default Constraint unnamed constraint on [dbo].[OrderItems]...';


GO
ALTER TABLE [dbo].[OrderItems]
    ADD DEFAULT (getdate()) FOR [DateUpdated];


GO
PRINT N'Creating Default Constraint unnamed constraint on [dbo].[OrderItems]...';


GO
ALTER TABLE [dbo].[OrderItems]
    ADD DEFAULT (getdate()) FOR [DateDeleted];


GO
PRINT N'Creating Default Constraint unnamed constraint on [dbo].[OrderItems]...';


GO
ALTER TABLE [dbo].[OrderItems]
    ADD DEFAULT (getdate()) FOR [DateCreated];


GO
PRINT N'Creating Default Constraint unnamed constraint on [dbo].[OrderItems]...';


GO
ALTER TABLE [dbo].[OrderItems]
    ADD DEFAULT ((1)) FOR [IsActive];


GO
PRINT N'Creating Default Constraint unnamed constraint on [dbo].[Orders]...';


GO
ALTER TABLE [dbo].[Orders]
    ADD DEFAULT (getdate()) FOR [OrderDate];


GO
PRINT N'Creating Default Constraint unnamed constraint on [dbo].[Orders]...';


GO
ALTER TABLE [dbo].[Orders]
    ADD DEFAULT ('Pending') FOR [Status];


GO
PRINT N'Creating Default Constraint unnamed constraint on [dbo].[Orders]...';


GO
ALTER TABLE [dbo].[Orders]
    ADD DEFAULT (CONVERT([bit],(1))) FOR [IsActive];


GO
PRINT N'Creating Default Constraint unnamed constraint on [dbo].[Orders]...';


GO
ALTER TABLE [dbo].[Orders]
    ADD DEFAULT (getdate()) FOR [DateUpdated];


GO
PRINT N'Creating Default Constraint unnamed constraint on [dbo].[Orders]...';


GO
ALTER TABLE [dbo].[Orders]
    ADD DEFAULT (getdate()) FOR [DateDeleted];


GO
PRINT N'Creating Default Constraint unnamed constraint on [dbo].[Orders]...';


GO
ALTER TABLE [dbo].[Orders]
    ADD DEFAULT (getdate()) FOR [DateCreated];


GO
PRINT N'Creating Default Constraint unnamed constraint on [dbo].[Orders]...';


GO
ALTER TABLE [dbo].[Orders]
    ADD DEFAULT (CONVERT([bit],(0))) FOR [IsPaid];


GO
PRINT N'Creating Default Constraint unnamed constraint on [dbo].[PaymentMethods]...';


GO
ALTER TABLE [dbo].[PaymentMethods]
    ADD DEFAULT (CONVERT([bit],(1))) FOR [IsActive];


GO
PRINT N'Creating Default Constraint unnamed constraint on [dbo].[PaymentMethods]...';


GO
ALTER TABLE [dbo].[PaymentMethods]
    ADD DEFAULT (getdate()) FOR [DateUpdated];


GO
PRINT N'Creating Default Constraint unnamed constraint on [dbo].[PaymentMethods]...';


GO
ALTER TABLE [dbo].[PaymentMethods]
    ADD DEFAULT (getdate()) FOR [DateDeleted];


GO
PRINT N'Creating Default Constraint unnamed constraint on [dbo].[PaymentMethods]...';


GO
ALTER TABLE [dbo].[PaymentMethods]
    ADD DEFAULT (getdate()) FOR [DateCreated];


GO
PRINT N'Creating Default Constraint unnamed constraint on [dbo].[Payments]...';


GO
ALTER TABLE [dbo].[Payments]
    ADD DEFAULT (getdate()) FOR [PaymentDate];


GO
PRINT N'Creating Default Constraint unnamed constraint on [dbo].[Payments]...';


GO
ALTER TABLE [dbo].[Payments]
    ADD DEFAULT (CONVERT([bit],(1))) FOR [IsActive];


GO
PRINT N'Creating Default Constraint unnamed constraint on [dbo].[Payments]...';


GO
ALTER TABLE [dbo].[Payments]
    ADD DEFAULT (getdate()) FOR [DateUpdated];


GO
PRINT N'Creating Default Constraint unnamed constraint on [dbo].[Payments]...';


GO
ALTER TABLE [dbo].[Payments]
    ADD DEFAULT (getdate()) FOR [DateDeleted];


GO
PRINT N'Creating Default Constraint unnamed constraint on [dbo].[Payments]...';


GO
ALTER TABLE [dbo].[Payments]
    ADD DEFAULT (getdate()) FOR [DateCreated];


GO
PRINT N'Creating Default Constraint unnamed constraint on [dbo].[ProductCategories]...';


GO
ALTER TABLE [dbo].[ProductCategories]
    ADD DEFAULT (getdate()) FOR [DateCreated];


GO
PRINT N'Creating Default Constraint unnamed constraint on [dbo].[ProductCategories]...';


GO
ALTER TABLE [dbo].[ProductCategories]
    ADD DEFAULT (getdate()) FOR [DateUpdated];


GO
PRINT N'Creating Default Constraint unnamed constraint on [dbo].[ProductCategories]...';


GO
ALTER TABLE [dbo].[ProductCategories]
    ADD DEFAULT (getdate()) FOR [DateDeleted];


GO
PRINT N'Creating Default Constraint unnamed constraint on [dbo].[Products]...';


GO
ALTER TABLE [dbo].[Products]
    ADD DEFAULT (getdate()) FOR [DateCreated];


GO
PRINT N'Creating Default Constraint unnamed constraint on [dbo].[Products]...';


GO
ALTER TABLE [dbo].[Products]
    ADD DEFAULT (CONVERT([bit],(1))) FOR [IsActive];


GO
PRINT N'Creating Default Constraint unnamed constraint on [dbo].[Products]...';


GO
ALTER TABLE [dbo].[Products]
    ADD DEFAULT (getdate()) FOR [DateUpdated];


GO
PRINT N'Creating Default Constraint unnamed constraint on [dbo].[Products]...';


GO
ALTER TABLE [dbo].[Products]
    ADD DEFAULT (getdate()) FOR [DateDeleted];


GO
PRINT N'Creating Default Constraint unnamed constraint on [dbo].[Reviews]...';


GO
ALTER TABLE [dbo].[Reviews]
    ADD DEFAULT (CONVERT([bit],(1))) FOR [IsActive];


GO
PRINT N'Creating Default Constraint unnamed constraint on [dbo].[Reviews]...';


GO
ALTER TABLE [dbo].[Reviews]
    ADD DEFAULT (getdate()) FOR [DateUpdated];


GO
PRINT N'Creating Default Constraint unnamed constraint on [dbo].[Reviews]...';


GO
ALTER TABLE [dbo].[Reviews]
    ADD DEFAULT (getdate()) FOR [DateDeleted];


GO
PRINT N'Creating Default Constraint unnamed constraint on [dbo].[Reviews]...';


GO
ALTER TABLE [dbo].[Reviews]
    ADD DEFAULT (getdate()) FOR [DateCreated];


GO
PRINT N'Creating Default Constraint unnamed constraint on [dbo].[Shipments]...';


GO
ALTER TABLE [dbo].[Shipments]
    ADD DEFAULT (getdate()) FOR [ShipmentDate];


GO
PRINT N'Creating Default Constraint unnamed constraint on [dbo].[Shipments]...';


GO
ALTER TABLE [dbo].[Shipments]
    ADD DEFAULT (CONVERT([bit],(1))) FOR [IsActive];


GO
PRINT N'Creating Default Constraint unnamed constraint on [dbo].[Shipments]...';


GO
ALTER TABLE [dbo].[Shipments]
    ADD DEFAULT (getdate()) FOR [DateUpdated];


GO
PRINT N'Creating Default Constraint unnamed constraint on [dbo].[Shipments]...';


GO
ALTER TABLE [dbo].[Shipments]
    ADD DEFAULT (getdate()) FOR [DateDeleted];


GO
PRINT N'Creating Default Constraint unnamed constraint on [dbo].[Shipments]...';


GO
ALTER TABLE [dbo].[Shipments]
    ADD DEFAULT (getdate()) FOR [DateCreated];


GO
PRINT N'Creating Default Constraint unnamed constraint on [dbo].[Subcategories]...';


GO
ALTER TABLE [dbo].[Subcategories]
    ADD DEFAULT (CONVERT([bit],(1))) FOR [IsActive];


GO
PRINT N'Creating Default Constraint unnamed constraint on [dbo].[Subcategories]...';


GO
ALTER TABLE [dbo].[Subcategories]
    ADD DEFAULT (getdate()) FOR [DateUpdated];


GO
PRINT N'Creating Default Constraint unnamed constraint on [dbo].[Subcategories]...';


GO
ALTER TABLE [dbo].[Subcategories]
    ADD DEFAULT (getdate()) FOR [DateDeleted];


GO
PRINT N'Creating Default Constraint unnamed constraint on [dbo].[Subcategories]...';


GO
ALTER TABLE [dbo].[Subcategories]
    ADD DEFAULT (getdate()) FOR [DateCreated];


GO
PRINT N'Creating Default Constraint unnamed constraint on [dbo].[Users]...';


GO
ALTER TABLE [dbo].[Users]
    ADD DEFAULT (N'') FOR [FirstName];


GO
PRINT N'Creating Default Constraint unnamed constraint on [dbo].[Users]...';


GO
ALTER TABLE [dbo].[Users]
    ADD DEFAULT (CONVERT([bit],(0))) FOR [IsAuthenticated];


GO
PRINT N'Creating Default Constraint unnamed constraint on [dbo].[Users]...';


GO
ALTER TABLE [dbo].[Users]
    ADD DEFAULT (N'') FOR [LastName];


GO
PRINT N'Creating Foreign Key [dbo].[FK__Addresses__Count__03F0984C]...';


GO
ALTER TABLE [dbo].[Addresses] WITH NOCHECK
    ADD CONSTRAINT [FK__Addresses__Count__03F0984C] FOREIGN KEY ([CountryId]) REFERENCES [dbo].[Countries] ([Id]) ON DELETE CASCADE;


GO
PRINT N'Creating Foreign Key [dbo].[FK__Addresses__Custo__02FC7413]...';


GO
ALTER TABLE [dbo].[Addresses] WITH NOCHECK
    ADD CONSTRAINT [FK__Addresses__Custo__02FC7413] FOREIGN KEY ([CustomerId]) REFERENCES [dbo].[Customers] ([Id]) ON DELETE CASCADE;


GO
PRINT N'Creating Foreign Key [dbo].[FK__Customers__UserI__5BE2A6F2]...';


GO
ALTER TABLE [dbo].[Customers] WITH NOCHECK
    ADD CONSTRAINT [FK__Customers__UserI__5BE2A6F2] FOREIGN KEY ([UserId]) REFERENCES [dbo].[Users] ([Id]) ON DELETE CASCADE;


GO
PRINT N'Creating Foreign Key [dbo].[FK__DeliveryM__Deliv__25518C17]...';


GO
ALTER TABLE [dbo].[DeliveryMethodOrders] WITH NOCHECK
    ADD CONSTRAINT [FK__DeliveryM__Deliv__25518C17] FOREIGN KEY ([DeliveryMethodId]) REFERENCES [dbo].[DeliveryMethods] ([Id]) ON DELETE CASCADE;


GO
PRINT N'Creating Foreign Key [dbo].[FK__DeliveryM__Order__2645B050]...';


GO
ALTER TABLE [dbo].[DeliveryMethodOrders] WITH NOCHECK
    ADD CONSTRAINT [FK__DeliveryM__Order__2645B050] FOREIGN KEY ([OrderId]) REFERENCES [dbo].[Orders] ([Id]) ON DELETE CASCADE;


GO
PRINT N'Creating Foreign Key [dbo].[FK__Invoice__Custome__32AB8735]...';


GO
ALTER TABLE [dbo].[Invoice] WITH NOCHECK
    ADD CONSTRAINT [FK__Invoice__Custome__32AB8735] FOREIGN KEY ([CustomerId]) REFERENCES [dbo].[Customers] ([Id]) ON DELETE CASCADE;


GO
PRINT N'Creating Foreign Key [dbo].[FK__Invoice__Payment__339FAB6E]...';


GO
ALTER TABLE [dbo].[Invoice] WITH NOCHECK
    ADD CONSTRAINT [FK__Invoice__Payment__339FAB6E] FOREIGN KEY ([PaymentId]) REFERENCES [dbo].[Payments] ([Id]);


GO
PRINT N'Creating Foreign Key [dbo].[FK__InvoiceIt__Invoi__395884C4]...';


GO
ALTER TABLE [dbo].[InvoiceItem] WITH NOCHECK
    ADD CONSTRAINT [FK__InvoiceIt__Invoi__395884C4] FOREIGN KEY ([InvoiceId]) REFERENCES [dbo].[Invoice] ([Id]) ON DELETE CASCADE;


GO
PRINT N'Creating Foreign Key [dbo].[FK__InvoiceIt__Produ__3A4CA8FD]...';


GO
ALTER TABLE [dbo].[InvoiceItem] WITH NOCHECK
    ADD CONSTRAINT [FK__InvoiceIt__Produ__3A4CA8FD] FOREIGN KEY ([ProductId]) REFERENCES [dbo].[Products] ([Id]) ON DELETE CASCADE;


GO
PRINT N'Creating Foreign Key [dbo].[FK__Orders__Customer__6383C8BA]...';


GO
ALTER TABLE [dbo].[Orders] WITH NOCHECK
    ADD CONSTRAINT [FK__Orders__Customer__6383C8BA] FOREIGN KEY ([CustomerId]) REFERENCES [dbo].[Customers] ([Id]) ON DELETE CASCADE;


GO
PRINT N'Creating Foreign Key [dbo].[FK_Payments_PaymentMethods_PaymentMethodId]...';


GO
ALTER TABLE [dbo].[Payments] WITH NOCHECK
    ADD CONSTRAINT [FK_Payments_PaymentMethods_PaymentMethodId] FOREIGN KEY ([PaymentMethodId]) REFERENCES [dbo].[PaymentMethods] ([Id]);


GO
PRINT N'Creating Foreign Key [dbo].[FK__Payments__OrderI__75A278F5]...';


GO
ALTER TABLE [dbo].[Payments] WITH NOCHECK
    ADD CONSTRAINT [FK__Payments__OrderI__75A278F5] FOREIGN KEY ([OrderId]) REFERENCES [dbo].[Orders] ([Id]) ON DELETE SET NULL;


GO
PRINT N'Creating Foreign Key [dbo].[FK__ProductCa__Categ__5535A963]...';


GO
ALTER TABLE [dbo].[ProductCategories] WITH NOCHECK
    ADD CONSTRAINT [FK__ProductCa__Categ__5535A963] FOREIGN KEY ([CategoryId]) REFERENCES [dbo].[Categories] ([Id]);


GO
PRINT N'Creating Foreign Key [dbo].[FK__ProductCa__Produ__5441852A]...';


GO
ALTER TABLE [dbo].[ProductCategories] WITH NOCHECK
    ADD CONSTRAINT [FK__ProductCa__Produ__5441852A] FOREIGN KEY ([ProductId]) REFERENCES [dbo].[Products] ([Id]);


GO
PRINT N'Creating Foreign Key [dbo].[FK_Products_Subcategories_SubcategoryId]...';


GO
ALTER TABLE [dbo].[Products] WITH NOCHECK
    ADD CONSTRAINT [FK_Products_Subcategories_SubcategoryId] FOREIGN KEY ([SubcategoryId]) REFERENCES [dbo].[Subcategories] ([Id]) ON DELETE CASCADE;


GO
PRINT N'Creating Foreign Key [dbo].[FK__Reviews__Custome__0B91BA14]...';


GO
ALTER TABLE [dbo].[Reviews] WITH NOCHECK
    ADD CONSTRAINT [FK__Reviews__Custome__0B91BA14] FOREIGN KEY ([CustomerId]) REFERENCES [dbo].[Customers] ([Id]) ON DELETE CASCADE;


GO
PRINT N'Creating Foreign Key [dbo].[FK__Reviews__Product__0A9D95DB]...';


GO
ALTER TABLE [dbo].[Reviews] WITH NOCHECK
    ADD CONSTRAINT [FK__Reviews__Product__0A9D95DB] FOREIGN KEY ([ProductId]) REFERENCES [dbo].[Products] ([Id]) ON DELETE CASCADE;


GO
PRINT N'Creating Foreign Key [dbo].[FK__Shipments__Deliv__1F98B2C1]...';


GO
ALTER TABLE [dbo].[Shipments] WITH NOCHECK
    ADD CONSTRAINT [FK__Shipments__Deliv__1F98B2C1] FOREIGN KEY ([DeliveryMethodId]) REFERENCES [dbo].[DeliveryMethods] ([Id]) ON DELETE CASCADE;


GO
PRINT N'Creating Foreign Key [dbo].[FK__Shipments__Order__1EA48E88]...';


GO
ALTER TABLE [dbo].[Shipments] WITH NOCHECK
    ADD CONSTRAINT [FK__Shipments__Order__1EA48E88] FOREIGN KEY ([OrderId]) REFERENCES [dbo].[Orders] ([Id]) ON DELETE CASCADE;


GO
PRINT N'Creating Foreign Key [dbo].[FK_ShoppingCartItems_Products_ProductId]...';


GO
ALTER TABLE [dbo].[ShoppingCartItems] WITH NOCHECK
    ADD CONSTRAINT [FK_ShoppingCartItems_Products_ProductId] FOREIGN KEY ([ProductId]) REFERENCES [dbo].[Products] ([Id]) ON DELETE CASCADE;


GO
PRINT N'Creating Foreign Key [dbo].[FK_Subcategories_Categories_CategoryId]...';


GO
ALTER TABLE [dbo].[Subcategories] WITH NOCHECK
    ADD CONSTRAINT [FK_Subcategories_Categories_CategoryId] FOREIGN KEY ([CategoryId]) REFERENCES [dbo].[Categories] ([Id]) ON DELETE CASCADE;


GO
PRINT N'Checking existing data against newly created constraints';


GO
USE [$(DatabaseName)];


GO
ALTER TABLE [dbo].[Addresses] WITH CHECK CHECK CONSTRAINT [FK__Addresses__Count__03F0984C];

ALTER TABLE [dbo].[Addresses] WITH CHECK CHECK CONSTRAINT [FK__Addresses__Custo__02FC7413];

ALTER TABLE [dbo].[Customers] WITH CHECK CHECK CONSTRAINT [FK__Customers__UserI__5BE2A6F2];

ALTER TABLE [dbo].[DeliveryMethodOrders] WITH CHECK CHECK CONSTRAINT [FK__DeliveryM__Deliv__25518C17];

ALTER TABLE [dbo].[DeliveryMethodOrders] WITH CHECK CHECK CONSTRAINT [FK__DeliveryM__Order__2645B050];

ALTER TABLE [dbo].[Invoice] WITH CHECK CHECK CONSTRAINT [FK__Invoice__Custome__32AB8735];

ALTER TABLE [dbo].[Invoice] WITH CHECK CHECK CONSTRAINT [FK__Invoice__Payment__339FAB6E];

ALTER TABLE [dbo].[InvoiceItem] WITH CHECK CHECK CONSTRAINT [FK__InvoiceIt__Invoi__395884C4];

ALTER TABLE [dbo].[InvoiceItem] WITH CHECK CHECK CONSTRAINT [FK__InvoiceIt__Produ__3A4CA8FD];

ALTER TABLE [dbo].[Orders] WITH CHECK CHECK CONSTRAINT [FK__Orders__Customer__6383C8BA];

ALTER TABLE [dbo].[Payments] WITH CHECK CHECK CONSTRAINT [FK_Payments_PaymentMethods_PaymentMethodId];

ALTER TABLE [dbo].[Payments] WITH CHECK CHECK CONSTRAINT [FK__Payments__OrderI__75A278F5];

ALTER TABLE [dbo].[ProductCategories] WITH CHECK CHECK CONSTRAINT [FK__ProductCa__Categ__5535A963];

ALTER TABLE [dbo].[ProductCategories] WITH CHECK CHECK CONSTRAINT [FK__ProductCa__Produ__5441852A];

ALTER TABLE [dbo].[Products] WITH CHECK CHECK CONSTRAINT [FK_Products_Subcategories_SubcategoryId];

ALTER TABLE [dbo].[Reviews] WITH CHECK CHECK CONSTRAINT [FK__Reviews__Custome__0B91BA14];

ALTER TABLE [dbo].[Reviews] WITH CHECK CHECK CONSTRAINT [FK__Reviews__Product__0A9D95DB];

ALTER TABLE [dbo].[Shipments] WITH CHECK CHECK CONSTRAINT [FK__Shipments__Deliv__1F98B2C1];

ALTER TABLE [dbo].[Shipments] WITH CHECK CHECK CONSTRAINT [FK__Shipments__Order__1EA48E88];

ALTER TABLE [dbo].[ShoppingCartItems] WITH CHECK CHECK CONSTRAINT [FK_ShoppingCartItems_Products_ProductId];

ALTER TABLE [dbo].[Subcategories] WITH CHECK CHECK CONSTRAINT [FK_Subcategories_Categories_CategoryId];


GO
PRINT N'Update complete.';


GO
